export const constants = {
    MAX_PAGE_SIZE: 50,
    DEFAULT_PAGE_SIZE: 10,
    JWT_EXPIRY: '7d',
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 100,
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 50,
  };